on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/rust-toolchain@stable
      - uses: actions/wasm-pack-action@v0.4.0
      - uses: actions/checkout@v4
      - run: wasm-pack build --target web --release
      - uses: actions/upload-artifact@v3
        with:
          path: pkg/*
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/deploy@main
